In [1]:
import numpy as np
import pandas as pd
print("Librerías cargadas correctamente")

Librerías cargadas correctamente

In [3]:
# Exploración de dataset IMDB movies
df_imdb = pd.read_csv('../data/raw/IMDb movies.csv')
print(f"Dataset Shape: {df_imdb.shape}")
print(f"\nColumnas:")
print(df_imdb.columns.tolist())

Dataset Shape: (81273, 23)

Columnas:
['index', 'imdb_title_id', 'title', 'original_title', 'year', 'date_published', 'genre', 'duration', 'country', 'language', 'director', 'writer', 'production_company', 'actors', 'description', 'avg_vote', 'votes', 'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore', 'reviews_from_users', 'reviews_from_critics']

In [4]:
# Revision de null y dtype
print(df_imdb.isnull().sum()) 
print(f"\nTipos de datos:")
print(df_imdb.dtypes)

index                        0
imdb_title_id                0
title                        0
original_title               0
year                         0
date_published               0
genre                        0
duration                     0
country                     39
language                   811
director                    73
writer                    1493
production_company        4325
actors                      66
description               2430
avg_vote                     0
votes                        0
budget                   58469
usa_gross_income         66179
worlwide_gross_income    51381
metascore                68551
reviews_from_users        7077
reviews_from_critics     10987
dtype: int64

Tipos de datos:
index                      int64
imdb_title_id                str
title                        str
original_title               str
year                       int64
date_published               str
genre                        str
duration                   int64
country                      str
language                     str
director                     str
writer                       str
production_company           str
actors                       str
description                  str
avg_vote                 float64
votes                      int64
budget                       str
usa_gross_income             str
worlwide_gross_income        str
metascore                float64
reviews_from_users       float64
reviews_from_critics     float64
dtype: object

In [5]:
# Dataset IMDb names
df_names = pd.read_csv('../data/raw/IMDb names.csv')
print(f"Dataset Shape: {df_names.shape}")
print(f"\nColumnas")
print(df_names.columns.tolist())
print(f"\nDataset Head:")
df_names.head()

Dataset Shape: (81273, 23)

Columnas
['index', 'imdb_title_id', 'title', 'original_title', 'year', 'date_published', 'genre', 'duration', 'country', 'language', 'director', 'writer', 'production_company', 'actors', 'description', 'avg_vote', 'votes', 'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore', 'reviews_from_users', 'reviews_from_critics']

Dataset Head:

,index,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,...,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
0,0,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,12/26/1906,"Biography, Crime, Drama",70,Australia,NaN,...,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,537,"$2,250",NaN,NaN,NaN,7.0,7.0
1,1,tt0001892,Den sorte drøm,Den sorte drøm,1911,8/19/1911,Drama,53,"Germany, Denmark",NaN,...,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.9,171,NaN,NaN,NaN,NaN,4.0,2.0
2,2,tt0002101,Cleopatra,Cleopatra,1912,11/13/1912,"Drama, History",100,USA,English,...,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,420,"$45,000",NaN,NaN,NaN,24.0,3.0
3,3,tt0002130,L'Inferno,L'Inferno,1911,3/6/1911,"Adventure, Drama, Fantasy",68,Italy,Italian,...,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2019,NaN,NaN,NaN,NaN,28.0,14.0
4,4,tt0002199,"From the Manger to the Cross; or, Jesus of Naz...","From the Manger to the Cross; or, Jesus of Naz...",1912,1913,"Biography, Drama",60,USA,English,...,"R. Henderson Bland, Percy Dyer, Gene Gauntier,...","An account of the life of Jesus Christ, based ...",5.7,438,NaN,NaN,NaN,NaN,12.0,5.0

In [6]:
print(df_imdb.equals(df_names))

False

In [7]:
# Comprobar datos de movies y names
# Se descartara names
print(f"IMDb movies Shape: {df_imdb.shape}")
print(f"IMDb names Shape: {df_names.shape}")
print(f"\nFila 1 IMDb movies:")
print(df_imdb.iloc[0]['title'])
print(f"\nFila 1 IMDb names:")
print(df_names.iloc[0]['title'])

IMDb movies Shape: (81273, 23)
IMDb names Shape: (81273, 23)

Fila 1 IMDb movies:
The Story of the Kelly Gang

Fila 1 IMDb names:
The Story of the Kelly Gang

In [8]:
df_cameras = pd.read_csv('../data/raw/camera_dataset.csv')
print(f"Dataset Shape: {df_cameras.shape}")
print(f"\nColumnas:")
print(df_cameras.columns.tolist())
print(f"\nDataset Head:")
df_cameras.head()

Dataset Shape: (1038, 13)

Columnas:
['Model', 'Release date', 'Max resolution', 'Low resolution', 'Effective pixels', 'Zoom wide (W)', 'Zoom tele (T)', 'Normal focus range', 'Macro focus range', 'Storage included', 'Weight (inc. batteries)', 'Dimensions', 'Price']

Dataset Head:

,Model,Release date,Max resolution,Low resolution,Effective pixels,Zoom wide (W),Zoom tele (T),Normal focus range,Macro focus range,Storage included,Weight (inc. batteries),Dimensions,Price
0,Agfa ePhoto 1280,1997,1024.0,640.0,0.0,38.0,114.0,70.0,40.0,4.0,420.0,95.0,179.0
1,Agfa ePhoto 1680,1998,1280.0,640.0,1.0,38.0,114.0,50.0,0.0,4.0,420.0,158.0,179.0
2,Agfa ePhoto CL18,2000,640.0,0.0,0.0,45.0,45.0,0.0,0.0,2.0,0.0,0.0,179.0
3,Agfa ePhoto CL30,1999,1152.0,640.0,0.0,35.0,35.0,0.0,0.0,4.0,0.0,0.0,269.0
4,Agfa ePhoto CL30 Clik!,1999,1152.0,640.0,0.0,43.0,43.0,50.0,0.0,40.0,300.0,128.0,1299.0